### ISSUE TITLE
Implement better config file location

### ISSUE THREAD

**Issue by ktoso** [typesafehub/sbt-java-formatter#11]
Given:

```
subproject/formatting.xml
subproject/src/...      // should use `/subproject/formatting.xml`
src/...                 // should use `/formatting.xml`
formatting.xml 
other/src/...           // should use `/formatting.xml`
```

This way a sub project can be formatted using a different style if needed.

**Comment by bantonsson** [comment]
I think that these should all fall back to the base `project/formatting.xml`

**Comment by ktoso** [comment]
So:

```
a/project/formatting.xml
a/formatting.xml
project/formatting.xml
formatting.xml
```

?

**Comment by bantonsson** [comment]
Sorry for all the confusion @ktoso, I think that I'm mixing up the settings in the plugin with the settings in our project. Yes, that would probably be a good order.

**Comment by ktoso** [comment]
No prob, thanks for chiming in :)
