### ISSUE TITLE
Make public + release

### ISSUE THREAD

**Issue by ktoso** [typesafehub/sbt-java-formatter#3]
We'd like to use this in Akka, as people contributing Java code (for Akka HTTP) have settings all over the place, so we have spaces, tabs, 4 spaces, 2 spaces and everthing in between sometimes. Would want to just have a formatter there.

**Comment by bantonsson** [comment]
Public and push should be done now...

**Comment by ktoso** [comment]
Thanks a lot, confirmed.
I'll polish the PR and proveed then

**Comment by ktoso** [comment]
Done
