### ISSUE TITLE
Add travis

### ISSUE THREAD

**Issue by ktoso** [typesafehub/sbt-java-formatter#4]
I don't have admin rights in this repo so can't do it.
Admin me or please add travis :)

**Comment by ktoso** [comment]
I added the file already, but needs enabling on travis-ci.org

https://github.com/typesafehub/sbt-java-formatter/blob/master/.travis.yml

**Comment by henrikengstrom** [comment]
@ktoso Added you as admin, so now you can do your thing :)

**Comment by ktoso** [comment]
Excellent, this is how I like to roll. 😎
